name: Start automated tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Specify ENV: NL, SR, CA'
        type: choice
        required: true
        options:
        - nl_test
        - nl_dev
        - sr_test
        - sr_dev
        - ca_test
        - ca_dev
      choice:
        type: choice
        description: Choose a Team
        required: true
        options:
        - Team1
        - Team2
        - Team3
        - Team4
        - Team5
      dropdown_values:
        description: 'Select options from both dropdowns'
        type: choice
        required: true
        default: "OptionA-OptionX"
        options:
        - test
        - test2
        - test3
      
      
      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install GitPython
        run: | 
          pip install GitPython
          pip install pyyaml
          pip install PyGithub
          pip install ruamel.yaml

      - name: Set PYTHONPATH
        run: |
          echo "export PYTHONPATH=\$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Execute Tests
 
        run: |
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "choice is ${{ github.event.inputs.choice }}" / ${{ inputs.choice }}
          python src/run.py ${{ inputs.environment }} ${{ inputs.choice }}
